"""Verify an isolated real pipeline run's Analyst/request path without paid APIs.

First run verify_storage_pipeline.py with a fresh --label, then pass its database
here. All clips generated by this script live in an automatically deleted folder.
ffprobe must be installed or passed with --ffprobe.
"""
import argparse
import json
from pathlib import Path
import subprocess
import sys
import tempfile
from unittest.mock import MagicMock, patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--database', required=True)
    parser.add_argument('--ffprobe', default='ffprobe')
    args = parser.parse_args()
    if Path(args.ffprobe).is_file():
        args.ffprobe = str(Path(args.ffprobe).resolve())
    import cv2
    import numpy as np
    import config
    from agents.reasoning_agent import SecurityAnalyst
    from langchain_core.runnables import RunnableLambda
    from storage.clips import clip_window
    from storage.repository import Repository
    from streamlit.testing.v1 import AppTest
    from utils.log_analyzer import LogAnalyzer
    from langchain_core.documents import Document

    with tempfile.TemporaryDirectory(prefix='incident_') as directory, \
         patch.object(config, 'DATABASE_URL', 'sqlite:///' + str(Path(args.database).resolve())), \
         patch.object(config, 'CLIP_CACHE_DIR', str(Path(directory)/'clips')), \
         patch.object(config, 'VECTOR_DB_PATH', str(Path(directory)/'vectors')), \
         patch('agents.retriever.OpenAIEmbeddings'), patch('agents.retriever.Chroma') as chroma, \
         patch('agents.reasoning_agent.ChatOpenAI', return_value=RunnableLambda(lambda x: x)):
        records = LogAnalyzer().get_narration_records()
        with Repository() as repository:
            assert repository.get_runs()[-1]['status'] == 'completed'
        docs = [Document(page_content=text,metadata=m) for text,m in records]
        # Choose an incident away from the start so pre-roll is also exercised.
        doc = next(d for d in docs if d.metadata['frame_no'] > 300 and d.metadata['action'] in ('Access','Intrusion','Removal','Theft'))
        chroma.from_documents.return_value.similarity_search.return_value = [doc]
        analyst = SecurityAnalyst(run_id=doc.metadata['run_id'])
        analyst.chain = MagicMock()
        analyst.chain.invoke.return_value.content = json.dumps(dict(
            answer_text=doc.page_content, cited_sources=[1]))
        app = AppTest.from_string('import streamlit as st\n'
            'from agents.analyst_ui import analyst_chat\nanalyst_chat(st.session_state.test_analyst)')
        app.session_state['test_analyst'] = analyst
        app.run()
        app.chat_input[0].set_value('What happened to ' + doc.metadata['person'] + '?').run()
        assert not app.exception, app.exception
        assert not Path(config.CLIP_CACHE_DIR).exists(), 'Text answer generated a clip!'
        assert not app.get('video'), 'Text answer loaded video!'
        assert not app.expander and not app.button
        app.chat_input[0].set_value('show me the footage').run(timeout=120)
        assert not app.exception, app.exception
        assert not app.warning, app.warning
        files = list(Path(config.CLIP_CACHE_DIR).glob('*.mp4'))
        assert len(files) == 1
        video = app.get('video')[0]
        assert not video.proto.autoplay
        probe = json.loads(subprocess.check_output([args.ffprobe, '-v','error','-select_streams','v:0',
            '-show_entries','stream=codec_name,pix_fmt,duration,nb_frames','-of','json',str(files[0])],text=True))['streams'][0]
        assert probe['codec_name'] == 'h264' and probe['pix_fmt'] == 'yuv420p'
        with Repository() as repository:
            source = repository.get_clip_source(doc.metadata['source_type'],doc.metadata['source_id'])
        original = cv2.VideoCapture(source['source_path'])
        clipped = cv2.VideoCapture(str(files[0]))
        try:
            fps = original.get(cv2.CAP_PROP_FPS)
            start,end = clip_window(source['frame_no'], fps, original.get(cv2.CAP_PROP_FRAME_COUNT),
                                    config.CLIP_PRE_SECONDS,config.CLIP_POST_SECONDS)
            assert abs(float(probe['duration']) - (end-start)) <= 1/fps + .001
            comparisons = []
            for clip_frame, source_frame in [(0,round(start*fps)),
                    (round((source['frame_no']-1)/fps*fps-start*fps),source['frame_no']-1)]:
                original.set(cv2.CAP_PROP_POS_FRAMES,source_frame)
                clipped.set(cv2.CAP_PROP_POS_FRAMES,clip_frame)
                ok_a,a = original.read()
                ok_b,b = clipped.read()
                assert ok_a and ok_b
                mae = float(np.abs(a.astype(float)-b.astype(float)).mean())
                assert mae < 5, mae
                comparisons.append(dict(clip_frame=clip_frame,source_frame_zero_based=source_frame,mae=mae))
        finally:
            original.release()
            clipped.release()
        result = dict(source_id=doc.metadata['source_id'], frame_no=source['frame_no'],
                      source_fps=fps, start_seconds=start, end_seconds=end,
                      ffprobe=probe,frame_comparisons=comparisons,
                      no_clip_before_request=True,autoplay=False)
        print(json.dumps(result,indent=2))


if __name__ == '__main__':
    main()
